version: "3.7"

services:
  mysql:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '01234'
      MYSQL_DATABASE: 'recycla-score'
    volumes:
      - db:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
        - 3306:3306

volumes:
  db: