name: Recycla-score backend build

on:
  push:
    branches: [ "master", "prod" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build docker image
      run: docker-compose up --build -d
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache SonarQube packages
      uses: actions/cache@v1
      with:
       path: ~/.sonar/cache
       key: ${{ runner.os }}-sonar
       restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
       restore-keys: ${{ runner.os }}-m2
    - name: Wait for MySQL
      uses: jakejarvis/wait-action@master
      with:
       time: '30s'
       host: mysql
       port: 3306
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create Tag and Deploy to AWS
      if: github.ref == 'refs/heads/prod'
      run: |
        TAG_NAME=$(date +v%Y%m%d%H%M%S)
        git tag $TAG_NAME
        git push origin $TAG_NAME
        pip install --upgrade awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region eu-west-3c
        aws elasticbeanstalk create-application-version --application-name recycla-score --version-label $TAG_NAME --source-bundle S3Bucket="elasticbeanstalk-eu-west-3-525676794539",S3Key="recycla-score.zip"
        aws elasticbeanstalk update-environment --application-name recycla-score --environment-name Recycla-score-env --version-label $TAG_NAME