name: Recycla-score backend build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build docker image
      run: docker-compose up --build -d
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache SonarQube packages
      uses: actions/cache@v1
      with:
       path: ~/.sonar/cache
       key: ${{ runner.os }}-sonar
       restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
       restore-keys: ${{ runner.os }}-m2
    - name: Wait for MySQL
      uses: jakejarvis/wait-action@master
      with:
       time: '30s'
       host: mysql
       port: 3306
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build and analyze
      env:
       SONAR_TOKEN: sqp_e6787a84a26f54211c7919769f5d12fbcf3e7f35
       SONAR_HOST_URL: http://localhost:9000
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=DayannD_recycla-score_AY1Gl665-yvVdE_JuAAi -Dsonar.projectName='recycla-score'
